# Generated by Django 2.1.7 on 2019-07-31 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_vt', models.CharField(db_column='nombre_Clasificacion_VT', max_length=45)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'CategoriaVt',
                'ordering': ['nombre_categoria_vt'],
            },
        ),
        migrations.CreateModel(
            name='Cip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cip', models.CharField(db_column='cod_CIP', max_length=45, unique=True)),
                ('desc_cip', models.TextField(blank=True, db_column='desc_CIP', null=True)),
                ('parent_cip', models.IntegerField(blank=True, db_column='parent_CIP', null=True)),
            ],
            options={
                'verbose_name': 'cip',
                'verbose_name_plural': 'cips',
                'db_table': 'CIP',
                'ordering': ['cod_cip'],
            },
        ),
        migrations.CreateModel(
            name='EcuacionPatente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Ecuacion')),
            ],
            options={
                'db_table': 'ecuacion_patente',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_estado', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'estados',
                'ordering': ['desc_estado'],
            },
        ),
        migrations.CreateModel(
            name='InventoresSolicitantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_inventor_solicitante', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'inventor_solicitante',
                'verbose_name_plural': 'inventores_solicitantes',
                'db_table': 'inventores_solicitantes',
                'ordering': ['nombre_inventor_solicitante'],
            },
        ),
        migrations.CreateModel(
            name='NumerosPatentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_serie_patente', models.CharField(max_length=20)),
                ('fecha_numero_patente', models.DateField()),
            ],
            options={
                'verbose_name': 'numero_patente',
                'verbose_name_plural': 'numeros_patentes',
                'db_table': 'numeros_patentes',
                'ordering': ['fecha_numero_patente'],
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pais', models.CharField(max_length=2)),
                ('desc_pais', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'pais',
                'verbose_name_plural': 'paises',
                'db_table': 'paises',
                'ordering': ['desc_pais'],
            },
        ),
        migrations.CreateModel(
            name='PatenteCatvt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_vt_id_categoria_vt', models.ForeignKey(db_column='categoria_vt_id_categoria_vt', on_delete=django.db.models.deletion.CASCADE, to='scraper.CategoriaVt')),
            ],
            options={
                'db_table': 'patente_catVT',
            },
        ),
        migrations.CreateModel(
            name='Patentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_patente', models.CharField(max_length=300)),
                ('resumen_patente', models.TextField(blank=True, null=True)),
                ('claims_patente', models.TextField(blank=True, null=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Cip')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Estados')),
            ],
            options={
                'verbose_name': 'patente',
                'verbose_name_plural': 'patentes',
                'db_table': 'patentes',
                'ordering': ['titulo_patente'],
            },
        ),
        migrations.CreateModel(
            name='PatentesRepositorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_patente_repositorio', models.CharField(max_length=100)),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Patentes')),
            ],
            options={
                'db_table': 'patentes_repositorios',
            },
        ),
        migrations.CreateModel(
            name='PatInvSol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pat_inv_sol', models.CharField(max_length=1)),
                ('inventor_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.InventoresSolicitantes')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Patentes')),
            ],
            options={
                'verbose_name': 'pat_inv_sol',
                'db_table': 'pat_inv_sol',
            },
        ),
        migrations.CreateModel(
            name='Repositorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repositorio', models.CharField(max_length=50)),
                ('link_repositorio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'repositorio',
                'verbose_name_plural': 'repositorios',
                'db_table': 'repositorios',
                'ordering': ['nombre_repositorio'],
            },
        ),
        migrations.CreateModel(
            name='TipoNumero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_numero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo_numero',
                'verbose_name_plural': 'tipos_numeros',
                'db_table': 'tipo_numero',
                'ordering': ['nombre_tipo_numero'],
            },
        ),
        migrations.CreateModel(
            name='TiposCip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_tip_cip', models.CharField(db_column='desc_tip_CIP', max_length=50, verbose_name='tipo de CIP')),
            ],
            options={
                'verbose_name': 'tipo_CIP',
                'verbose_name_plural': 'tipos_CIP',
                'db_table': 'tipos_CIP',
                'ordering': ['desc_tip_cip'],
            },
        ),
        migrations.AddField(
            model_name='patentesrepositorios',
            name='repositorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Repositorios'),
        ),
        migrations.AddField(
            model_name='patentecatvt',
            name='patentes_id_patente',
            field=models.ForeignKey(db_column='patentes_id_patente', on_delete=django.db.models.deletion.CASCADE, to='scraper.Patentes'),
        ),
        migrations.AddField(
            model_name='numerospatentes',
            name='num_pat_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Paises'),
        ),
        migrations.AddField(
            model_name='numerospatentes',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Patentes'),
        ),
        migrations.AddField(
            model_name='numerospatentes',
            name='tipo_numero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.TipoNumero'),
        ),
        migrations.AddField(
            model_name='ecuacionpatente',
            name='patente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.Patentes'),
        ),
        migrations.AddField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_CIP_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.TiposCip'),
        ),
    ]
