# Generated by Django 2.1.7 on 2019-08-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20190731_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposcip',
            options={'ordering': ['desc_tip_cip'], 'verbose_name': 'tipo_cip', 'verbose_name_plural': 'tipos_cip'},
        ),
        migrations.AlterField(
            model_name='cip',
            name='cod_cip',
            field=models.CharField(db_column='cod_cip', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='cip',
            name='desc_cip',
            field=models.TextField(blank=True, db_column='desc_cip', null=True),
        ),
        migrations.AlterField(
            model_name='cip',
            name='parent_cip',
            field=models.IntegerField(blank=True, db_column='parent_cip', null=True),
        ),
        migrations.AlterField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_cip_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.Tiposcip'),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cip'),
        ),
        migrations.AlterField(
            model_name='tiposcip',
            name='desc_tip_cip',
            field=models.CharField(db_column='desc_tip_cip', max_length=50, verbose_name='tipo de cip'),
        ),
        migrations.AlterModelTable(
            name='cip',
            table='cip',
        ),
        migrations.AlterModelTable(
            name='tiposcip',
            table='tipos_cip',
        ),
    ]
