# Generated by Django 2.1.7 on 2019-08-14 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20190813_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patinvsol',
            options={'ordering': ['tipo_pat_inv_sol'], 'verbose_name': 'pat_inv_sol'},
        ),
        migrations.AlterField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_cip_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.Tiposcip'),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cip'),
        ),
    ]
