# Generated by Django 2.1.7 on 2019-09-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20190814_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_cip_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.Tiposcip'),
        ),
        migrations.AlterField(
            model_name='numerospatentes',
            name='cod_serie_patente',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cip'),
        ),
    ]
