# Generated by Django 2.1.7 on 2019-09-13 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20190913_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patentes',
            options={'verbose_name': 'patente', 'verbose_name_plural': 'patentes'},
        ),
        migrations.AlterField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_cip_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.Tiposcip'),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cip'),
        ),
    ]
