# Generated by Django 2.1.7 on 2019-11-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20191107_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cip',
            name='tipo_cip',
            field=models.ForeignKey(db_column='tipo_cip_id', on_delete=django.db.models.deletion.CASCADE, to='scraper.Tiposcip'),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.cip'),
        ),
        migrations.AlterField(
            model_name='patentes',
            name='ecuacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Ecuacion'),
        ),
    ]
